{
    ["AK47"] = {
        "Precision",
        "Quantum",
        "Clown",
        "Maker",
        "Code Orange",
        "Outrunner",
        "Mean Green",
        "Bloodboom",
        "Hallows",
        "Survivor",
        "Eve",
        "Glo",
        "Gifted",
        "Patch",
        "Ugly Sweater",
        "VAV",
        "Godess",
        "Secret Santa",
        "Hypersonic",
        "Outlaws",
        "Scythe",
        "Yltude",
        "Variant Camo",
        "Ace",
        "Shooting Star",
        "Quicktime",
        "Neonline",
        "Scapter",
        "Skin Committee",
        "Ghost",
        "Halo",
        "Inversion",
        "Plated",
        "Jester",
        "Toxic Nitro"
    },
    ["AUG"] = {
        "Maker",
        "Homestead",
        "Phoenix",
        "Dream Hound",
        "Sunsthetic",
        "Enlisted",
        "NightHawk",
        "Graffiti"
    },
    ["AWP"] = {
        "Coffin Biter",
        "Autumness",
        "Forever",
        "Desert Camo",
        "Lunar",
        "Retroactive",
        "Instinct",
        "Grepkin",
        "Pink Vision",
        "Abaddon",
        "Racer",
        "Bloodborne",
        "Northern Lights",
        "Pear Tree",
        "Difference",
        "Blastech",
        "JTF2",
        "Weeb",
        "Darkness",
        "Regina",
        "Hika",
        "Pinkie",
        "Silence",
        "Illusion",
        "Oriental",
        "Scapter",
        "Nerf",
        "Dark Galaxy",
        "Blue",
        "Venomus",
        "Kumanjayi",
        "Dragon",
        "Quicktime",
        "Toxic Nitro"
    },
    ["Bizon"] = {
        "Shattered",
        "Sergeant",
        "Festive",
        "Autumic",
        "Oblivion",
        "Saint Nick"
    },
    ["CZ"] = {
        "Festive",
        "Designed",
        "Spectre",
        "Orange Web",
        "Lightning",
        "Hallow",
        "Holidays"
    },
    ["DesertEagle"] = {
        "Racer",
        "Cool Blue",
        "Krystallos",
        "Survivor",
        "ROLVe",
        "Pumpkin Buster",
        "Honor-bound",
        "Cold Truth",
        "Heat",
        "Glittery",
        "Grim",
        "DropX",
        "Independence",
        "Xmas",
        "Crystal",
        "Scapter",
        "Weeb",
        "TC",
        "Skin Committee"
    },
    ["DualBerettas"] = {
        "Old Fashioned",
        "Hexline",
        "Carbonized",
        "Neon web",
        "Xmas",
        "Floral",
        "Dusty Manor"
    },
    ["Famas"] = {
        "Cogged",
        "Abstract",
        "Medic",
        "KugaX",
        "MK11",
        "Haunted Forest",
        "Redux",
        "Centipede",
        "Goliath",
        "Toxic Rain",
        "Imprisioned",
        "Shocker"
    },
    ["FiveSeven"] = {
        "Fluid",
        "Mr. Anatomy",
        "Danjo",
        "Autumn Fade",
        "Stigma",
        "Sub Zero",
        "Summer",
        "Midnight Ride",
        "Gifted"
    },
    ["G3SG1"] = {
        "Mahogany",
        "Autumn",
        "Foliage",
        "Hex",
        "Amethyst",
        "Holly Bound"
    },
    ["Galil"] = {
        "Frosted",
        "Toxicity",
        "Hardware",
        "Hardware 2",
        "Worn"
    },
    ["Glock"] = {
        "Money Maker",
        "Anubis",
        "Rush",
        "Spacedust",
        "Wetland",
        "Angler",
        "Midnight Tiger",
        "Day Dreamer",
        "Desert Camo",
        "Tarnish",
        "Gravestomper",
        "Underwater",
        "Biotrip",
        "Scapter",
        "RSL"
    },
    ["M249"] = {
        "P2020",
        "Wolf",
        "Aggressor",
        "Spooky",
        "Lantern"
    },
    ["M4A1"] = {
        "Necropolis",
        "Impulse",
        "Desert Camo",
        "Burning",
        "Lunar",
        "Tecnician",
        "Wastelander",
        "Animatic",
        "Toucan",
        "Heavens Gate",
        "Jester"
    }
}